package main.java.com.marist.mscs721;

import java.util.ArrayList;

import org.junit.Test;

import junit.framework.TestCase;

/**
 * The class <code>Testcase2</code> contains tests for the class {@link
 * <code>RoomScheduler</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 4/12/16 7:42 PM
 *
 * @author Gopi
 *
 * @version $Revision$
 */
public class Testcase2 extends TestCase {
	ArrayList<Room> roomList = new ArrayList<Room>();
	@Test
	public void testAddRoom(){
	Room newRoom = new Room("a", 3, "2", "1234");
	roomList.add(newRoom);
	String status= RoomScheduler.addRoom(roomList);
	org.junit.Assert.assertEquals("Room added successfully!", status);
	}
}

	

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = com.marist.mscs721
 * package.sourceFolder = RoomScheduler/src
 * superclassType = junit.framework.TestCase
 * testCase = Testcase2
 * testClassType = com.marist.mscs721.RoomScheduler
 */