package com.marist.mscs721;


import java.util.ArrayList;

import junit.framework.TestCase;

import org.junit.Test;

/**
 * The class <code>RoomSchedulerTest</code> contains tests for the class {@link
 * <code>RoomScheduler</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 4/6/16 6:21 PM
 *
 * @author Gopi
 *
 * @version $Revision$
 */

public class Testcase1 extends TestCase{
	ArrayList<Room> roomList = new ArrayList<Room>();
	@Test
	public void testRemoveRoom(){
	Room newRoom = new Room("101", 2, "2", "1234");
	roomList.add(newRoom);
	String status= RoomScheduler.removeRoom(roomList);
	org.junit.Assert.assertEquals("Room removed successfully!", status);
	}
	
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = com.marist.mscs721
 * package.sourceFolder = RoomScheduler/src
 * superclassType = junit.framework.TestCase
 * testCase = RoomSchedulerTest
 * testClassType = RoomScheduler
 */